### ISSUE TITLE
Clarify things needed for full access to locally hosted Docker instance in README.md

### ISSUE THREAD

**Issue by gazecube** [osuTitanic/titanic#12]
In the Docker instructions, there isn't anything about the password of the "peppy" account, nor any instructions on how to manually edit the database tables to give yourself admin. We need these. Please. Add them to the readme.

**Comment by how-to-do-frontend** [comment]
just dont use docker ezpz

**Comment by Lekuruu** [comment]
I am not here to provide a docker/database 101 tutorial, but I should add the default password for peppy, yes.
There are a lot of tools out there for managing PostgreSQL Databases, and it's not that far away from MySQL.

**Comment by Lekuruu** [comment]
> just dont use docker ezpz

This problem does not really lie with docker here, if you would have read his issue.

But still, the docker setup is what I use in production and I would honestly recommend it to everyone, since the manual setup instructions have a much higher chance to cause issues, and also leave a lot of stuff out, like jobs or the discord bot.

**Comment by Lekuruu** [comment]
Resolved in https://github.com/osuTitanic/titanic/commit/11e0504ee93fb84b3c797eab2d74124e541c816e
